#version: '3'
#
#services:
#  web:
#    build: .
#    command: python manage.py runserver localhost:8000
#    volumes:
#      - .:/code
#    ports:
#      - "8000:8000"

version: '3'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python manage.py migrate && python manage.py runserver 0.0.0.0:8000
