# Generated by Django 4.1.7 on 2023-02-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_comment_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='home_page',
            field=models.URLField(blank=True, null=True),
        ),
    ]
